"""Arm C: deterministic mechanical contraction (decision 0007).

Iteratively remove decorative (source_ids == []) or contaminated claims to a fixpoint:
id-ascending, a single pass per iteration, no re-scoring within a pass. The contracted
conclusion is DERIVED from the surviving claims by a committed deterministic template — it
is never re-generated by the model (0007 derive-not-regenerate: the load-bearing choice that
makes the bit-for-bit regeneration check hold).

There is no code path accepting a per-task hand-authored contraction. contract() takes only
(scalar, sources, output) and the frozen detector config; the same inputs produce a
byte-identical serialized output.
"""

from __future__ import annotations

import json
from typing import Sequence

from .config import CONFIG, DetectorConfig
from .detector import is_contaminated
from .nli import Scalar
from .schema import Claim, Output


def _flagged(
    scalar: Scalar,
    sources: Sequence[str],
    claim: Claim,
    config: DetectorConfig,
) -> bool:
    # Decorative (structural, 0002) OR contaminated (0007).
    if not claim.source_ids:
        return True
    return is_contaminated(scalar, sources, claim, config)


def derive_conclusion(claims: Sequence[Claim]) -> str:
    """Committed deterministic conclusion template over surviving claims.

    Not model-generated. Deterministic in the surviving claim set: id-ascending claim texts
    joined into a single sentence. An empty survivor set yields the empty-support sentinel.
    """
    ordered = sorted(claims, key=lambda c: c.id)
    if not ordered:
        return "No claim survives contraction; no conclusion is supported."
    texts = [c.text.strip().rstrip(".") for c in ordered]
    return "Therefore, " + "; ".join(texts) + "."


def contract(
    scalar: Scalar,
    sources: Sequence[str],
    output: Output,
    config: DetectorConfig = CONFIG.detector,
) -> Output:
    """Contract an arm output to its fixpoint and derive the conclusion.

    Single pass per iteration over the survivors in id-ascending order: every survivor is
    evaluated once against the current source set, the flagged set is removed together, and
    the loop repeats until a pass removes nothing.
    """
    survivors: list[Claim] = sorted(output.claims, key=lambda c: c.id)

    while True:
        # One pass: evaluate every current survivor once (no re-scoring mid-pass).
        remove_ids = {
            c.id for c in survivors if _flagged(scalar, sources, c, config)
        }
        if not remove_ids:
            break
        survivors = [c for c in survivors if c.id not in remove_ids]

    survivors = sorted(survivors, key=lambda c: c.id)
    return Output(
        claims=tuple(survivors),
        conclusion=derive_conclusion(survivors),
    )


def serialize(output: Output) -> str:
    """Canonical byte-stable serialization for the reproducibility check (0007)."""
    payload = {
        "claims": [
            {"id": c.id, "text": c.text, "source_ids": list(c.source_ids)}
            for c in sorted(output.claims, key=lambda c: c.id)
        ],
        "conclusion": output.conclusion,
    }
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
